name: Terraform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate